package de.se.tinf11b3.breakdown.server.gui;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.CustomComponent;

import de.se.tinf11b3.breakdown.Canvas;
import de.se.tinf11b3.breakdown.server.spielverwaltung.Spielverwaltung;

public class Spielfenster extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private Canvas canvas_1;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public Spielfenster(Spielverwaltung spielverwaltung) {
		buildMainLayout(spielverwaltung);
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout(Spielverwaltung spielverwaltung) {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// canvas_1
		canvas_1 = new Canvas(spielverwaltung);
		canvas_1.setImmediate(false);
		canvas_1.setWidth("500px");
		canvas_1.setHeight("500px");
		mainLayout.addComponent(canvas_1, "top:10.0%;left:20.0%;");
		
		return mainLayout;
	}

}
