package de.se.tinf11b3.breakdown.server.gui;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.terminal.ThemeResource;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;

import de.se.tinf11b3.breakdown.Canvas;
import de.se.tinf11b3.breakdown.server.spielverwaltung.Spielverwaltung;

public class Spielfenster extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	private HorizontalLayout horizontalLayout_1;
	private Canvas canvas_1;
	private Label label_1;
	private Label label_2;
	private Label label_3;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public Spielfenster(Spielverwaltung spielverwaltung) {
		buildMainLayout(spielverwaltung);
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout(Spielverwaltung spielverwaltung) {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// horizontalLayout_1
		horizontalLayout_1 = buildHorizontalLayout_1();
		mainLayout.addComponent(horizontalLayout_1, "top:18.0px;left:60.0px;");


			

		
		// canvas_1
		canvas_1 = new Canvas(spielverwaltung);
		canvas_1.setImmediate(false);
		canvas_1.setWidth("500px");
		canvas_1.setHeight("500px");
		mainLayout.addComponent(canvas_1, "top:10.0%;left:20.0%;");
		
		return mainLayout;
	}
	
	@AutoGenerated
	private HorizontalLayout buildHorizontalLayout_1() {
		// common part: create layout
		horizontalLayout_1 = new HorizontalLayout();
		horizontalLayout_1.setImmediate(false);
		horizontalLayout_1.setWidth("-1px");
		horizontalLayout_1.setHeight("-1px");
		horizontalLayout_1.setMargin(false);
		
		// label_1
		label_1 = new Label();
		label_1.setIcon(new ThemeResource("k-Leben.png"));
		label_1.setImmediate(false);
		label_1.setWidth("50px");
		label_1.setHeight("63px");
		label_1.setValue(" ");
		horizontalLayout_1.addComponent(label_1);
		
		
		// label_2
		label_2 = new Label();
		label_2.setIcon(new ThemeResource("k-Leben.png"));
		label_2.setImmediate(false);
		label_2.setWidth("50px");
		label_2.setHeight("63px");
		label_2.setValue(" ");
		horizontalLayout_1.addComponent(label_2);
		
		
		// label_3
		label_3 = new Label();
		label_3.setIcon(new ThemeResource("k-Leben.png"));
		label_3.setImmediate(false);
		label_3.setWidth("50px");
		label_3.setHeight("63px");
		label_3.setValue(" ");
		horizontalLayout_1.addComponent(label_3);
		
		
		
		return horizontalLayout_1;
	}

}