package de.se.tinf11b3.breakdown.server.gui;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.terminal.ThemeResource;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;

import cucumber.annotation.lu.an;

import de.se.tinf11b3.breakdown.Canvas;
import de.se.tinf11b3.breakdown.server.spielverwaltung.Spielverwaltung;

public class Spielfenster extends CustomComponent{

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private Canvas canvas_1;
	@AutoGenerated
	private VerticalLayout verticalLayout_1;
	@AutoGenerated
	private Label label_5;
	@AutoGenerated
	private Label label_4;
	@AutoGenerated
	private HorizontalLayout horizontalLayout_1;
	@AutoGenerated
	private Label label_3;
	@AutoGenerated
	private Label label_2;
	@AutoGenerated
	private Label label_1;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public Spielfenster(Spielverwaltung spielverwaltung) {
		buildMainLayout(spielverwaltung);
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	public Canvas getCanvas_1() {
	return canvas_1;
}

@AutoGenerated
private AbsoluteLayout buildMainLayout(Spielverwaltung spielverwaltung) {
	// common part: create layout
	mainLayout = new AbsoluteLayout();
	mainLayout.setImmediate(false);
	mainLayout.setWidth("100%");
	mainLayout.setHeight("100%");
	mainLayout.setMargin(false);
	
	// top-level component properties
	setWidth("100.0%");
	setHeight("100.0%");
	
	// horizontalLayout_1
	horizontalLayout_1 = buildHorizontalLayout_1();
	mainLayout.addComponent(horizontalLayout_1, "top:18.0px;left:60.0px;");
	
	// verticalLayout_1
	verticalLayout_1 = buildVerticalLayout_1();
	mainLayout.addComponent(verticalLayout_1, "top:105.0px;left:60.0px;");
	
	// canvas_1
	canvas_1 = new Canvas(spielverwaltung);
	canvas_1.setImmediate(false);
	canvas_1.setWidth("500px");
	canvas_1.setHeight("500px");
	mainLayout.addComponent(canvas_1, "top:10.0%;left:20.0%;");
	
	return mainLayout;
}

@AutoGenerated
private HorizontalLayout buildHorizontalLayout_1() {
	// common part: create layout
	horizontalLayout_1 = new HorizontalLayout();
	horizontalLayout_1.setImmediate(false);
	horizontalLayout_1.setWidth("-1px");
	horizontalLayout_1.setHeight("-1px");
	horizontalLayout_1.setMargin(false);
	
	// label_1
	label_1 = new Label();
	label_1.setIcon(new ThemeResource("k-Leben.png"));
	label_1.setImmediate(false);
	label_1.setWidth("50px");
	label_1.setHeight("63px");
	label_1.setValue(" ");
	horizontalLayout_1.addComponent(label_1);
	
	// label_2
	label_2 = new Label();
	label_2.setIcon(new ThemeResource("k-Leben.png"));
	label_2.setImmediate(false);
	label_2.setWidth("50px");
	label_2.setHeight("63px");
	label_2.setValue(" ");
	horizontalLayout_1.addComponent(label_2);
	
	// label_3
	label_3 = new Label();
	label_3.setIcon(new ThemeResource("k-Leben.png"));
	label_3.setImmediate(false);
	label_3.setWidth("50px");
	label_3.setHeight("63px");
	label_3.setValue(" ");
	horizontalLayout_1.addComponent(label_3);
	
	return horizontalLayout_1;
}

@AutoGenerated
private VerticalLayout buildVerticalLayout_1() {
	// common part: create layout
	verticalLayout_1 = new VerticalLayout();
	verticalLayout_1.setImmediate(false);
	verticalLayout_1.setWidth("101px");
	verticalLayout_1.setHeight("55px");
	verticalLayout_1.setMargin(false);
	
	// label_4
	label_4 = new Label();
	label_4.setImmediate(false);
	label_4.setWidth("-1px");
	label_4.setHeight("-1px");
	label_4.setValue("Punkte:");
	verticalLayout_1.addComponent(label_4);
	
	// label_5
	label_5 = new Label();
	label_5.setImmediate(false);
	label_5.setWidth("-1px");
	label_5.setHeight("-1px");
	label_5.setValue("XXX");
	verticalLayout_1.addComponent(label_5);
	
	return verticalLayout_1;
}

	public void refreshHighscore(int wert) {
		this.label_5.setValue(wert);
	}

	public void setLeben(int anzahl) {
		switch(anzahl) {
			case 0:
				label_1.setVisible(false);
				label_2.setVisible(false);
				label_3.setVisible(false);
				break;
			case 1:
				label_1.setVisible(true);
				label_2.setVisible(false);
				label_3.setVisible(false);
				break;
			case 2:
				label_1.setVisible(true);
				label_2.setVisible(true);
				label_3.setVisible(false);
				break;
			case 3:
				label_1.setVisible(true);
				label_2.setVisible(true);
				label_3.setVisible(true);
				break;
			default:
				break;
		}
	}

}